export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_LOADING = 'FETCH_LOADING';

export const PUBLIC_INFORMATION_SUCCESS = 'PUBLIC_INFORMATION_SUCCESS';
export const PUBLIC_INFORMATION_LOADING = 'PUBLIC_INFORMATION_LOADING';
export const PUBLIC_INFORMATION_ERROR = 'PUBLIC_INFORMATION_ERROR';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING';

export const ACTIVATE_USER_LOADING = 'ACTIVATE_USER_LOADING';
export const ACTIVATE_USER = 'ACTIVATE_USER';   
export const ACTIVATE_USER_ERROR = 'ACTIVATE_USER_ERROR';

export const USER_SIGNUP_LOADING = 'USER_SIGNUP_LOADING';
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';
export const STORE_ID = 'STORE_ID';


export const GET_MY_PROFILE_LOADING = 'GET_MY_PROFILE_LOADING';
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_MY_PROFILE_ERROR = 'GET_MY_PROFILE_ERROR';


export const UPDATE_MY_PROFILE_LOADING = 'UPDATE_MY_PROFILE_LOADING';
export const UPDATE_MY_PROFILE_SUCCESS = 'UPDATE_MY_PROFILE_SUCCESS';
export const UPDATE_MY_PROFILE_ERROR = 'UPDATE_MY_PROFILE_ERROR';

export const SUCCESS_OTP_LOADING = 'SUCCESS_OTP_LOADING';
export const SUCCESS_OTP = 'SUCCESS_OTP';
export const FAIL_OTP = 'FAIL_OTP';

export const UPDATE_IN_BAG_LOADING = 'UPDATE_IN_BAG_LOADING';
export const UPDATE_IN_BAG = 'UPDATE_IN_BAG';
export const UPDATE_IN_ERROR = 'UPDATE_IN_ERROR';

export const RESCHEDULE_BOOKING_DATA_LOADING = 'RESCHEDULE_BOOKING_DATA_LOADING'
export const RESCHEDULE_BOOKING_DATA_SUCCESSFULLY = 'RESCHEDULE_BOOKING_DATA_SUCCESSFULLY'
export const RESCHEDULE_BOOKING_DATA_FAIL = 'RESCHEDULE_BOOKING_DATA_FAIL'

export const CANCEL_BOOKING_LOADING = 'CANCEL_BOOKING_LOADING'
export const CANCEL_BOOKING_SUCCESS = 'CANCEL_BOOKING_SUCCESS'
export const CANCEL_BOOKING_FAIL = 'CANCEL_BOOKING_FAIL'

export const ADDRESS_LOADING = 'ADDRESS_LOADING';
export const GET_ALL_ADDRESS = 'GET_ALL_ADDRESS';
export const POST_ADDRESS = 'POST_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';

export const SEARCH_ITEM_LOADING = 'SEARCH_ITEM_LOADING';
export const SEARCH_ITEM = 'SEARCH_ITEM';
export const GET_SEARCH_TYPE = 'GET_SEARCH_TYPE';
export const SEARCHED_QUARRY = 'SEARCHED_QUARRY';

export const GET_THEMES_LOADING = 'GET_THEMES_LOADING';
export const GET_THEMES = 'GET_THEMES';
export const GET_THEMES_ERROR = 'GET_THEMES_ERROR';
export const CHANGE_THEME = 'CHANGE_THEME';


export const CHECKED_OUT_SUCCESS_LOADING = 'CHECKED_OUT_SUCCESS_LOADING';
export const CHECKED_OUT_SUCCESS = 'CHECKED_OUT_SUCCESS';
export const CHECKED_OUT_FAIL = 'CHECKED_OUT_FAIL';


export const CHECKED_OUT_LIST_SUCCESS = 'CHECKED_OUT_LIST_SUCCESS';
export const CHECKED_OUT_LIST_FAIL = 'CHECKED_OUT_LIST_FAIL';

export const GET_ALL_COUPONS_SUCCESS_LOADING = 'GET_ALL_COUPONS_SUCCESS_LOADING'
export const GET_ALL_COUPONS_SUCCESS = 'GET_ALL_COUPONS_SUCCESS'
export const GET_ALL_COUPONS_FAIL = 'GET_ALL_COUPONS_FAIL'

export const POST_COUPON_CODE_SUCCESS = 'POST_COUPON_CODE_SUCCESS'
export const POST_COUPON_CODE_FAIL = 'POST_COUPON_CODE_FAIL'

export const OPEN_CHECKOUT_LIST = 'OPEN_CHECKOUT_LIST'
export const CLOSE_CHECKOUT_LIST = 'CLOSE_CHECKOUT_LIST'

export const UNKNOWN_USER_SUCCESS = 'UNKNOWN_USER_SUCCESS';
export const UNKNOWN_USER_ERROR = 'UNKNOWN_USER_ERROR';


export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

export const OPEN_REPEAT = 'OPEN_REPEAT';
export const CLOSE_REPEAT = 'CLOSE_REPEAT';

export const OPEN_VIEW_DIALOG = 'OPEN_VIEW_DIALOG';
export const CLOSE_VIEW_DIALOG = 'CLOSE_VIEW_DIALOG';

export const PROTECTED_ROUTE = 'PROTECTED_ROUTE';
export const ADD_PACKAGE = 'ADD_PACKAGE';


export const GET_ALL_CART_DATA = 'GET_ALL_CART_DATA';
export const GET_ALL_CART_DATA_ERROR = 'GET_ALL_CART_DATA_ERROR';

export const DELETE_IN_BAG = 'DELETE_IN_BAG';

export const INCREMENT_IN_U_BAG = 'INCREMENT_IN_U_BAG';
export const DECREMENT_IN_U_BAG = 'DECREMENT_IN_U_BAG';


export const OPEN_ADDRESS_ADD_DIALOG = 'OPEN_ADDRESS_ADD_DIALOG';
export const CLOSE_ADDRESS_ADD_DIALOG = 'CLOSE_ADDRESS_ADD_DIALOG';

export const OPEN_DELETE_ADDRESS_DIALOG = 'OPEN_DELETE_ADDRESS_DIALOG';
export const CLOSE_DELETE_ADDRESS_DIALOG = 'CLOSE_DELETE_ADDRESS_DIALOG';

export const OPEN_UPDATE_ADDRESS_DIALOG = 'OPEN_UPDATE_ADDRESS_DIALOG';
export const CLOSE_UPDATE_ADDRESS_DIALOG = 'CLOSE_UPDATE_ADDRESS_DIALOG';

export const APPLY_COUPON = 'APPLY_COUPON';
export const GET_SCHEDULE = 'GET_SCHEDULE';

export const GET_ORDER_DATA = 'GET_ORDER_DATA';
export const GET_ORDER_DATA_ERROR = 'GET_ORDER_DATA_ERROR';


export const BUTTON_THEME = 'BUTTON_THEME';


export const EMPTY_QUARRY = 'EMPTY_QUARRY';

export const OPEN_COUPON_DIALOG = 'OPEN_COUPON_DIALOG';
export const CLOSE_COUPON_DIALOG = 'CLOSE_COUPON_DIALOG';

export const SHOW_ALL_ADDRESS = 'SHOW_ALL_ADDRESS';
export const HIDE_ALL_ADDRESS = 'HIDE_ALL_ADDRESS';

export const OPEN_SCHEDULE_DIALOG = 'OPEN_SCHEDULE_DIALOG';
export const CLOSE_SCHEDULE_DIALOG = 'CLOSE_SCHEDULE_DIALOG';

export const OPEN_T_C_DIALOG = 'OPEN_T_C_DIALOG';
export const CLOSE_T_C_DIALOG = 'CLOSE_T_C_DIALOG';

export const OPEN_PROFILE_EDIT = 'OPEN_PROFILE_EDIT';
export const CLOSE_PROFILE_EDIT = 'CLOSE_PROFILE_EDIT';

export const OPEN_AGREE_BOX = 'OPEN_AGREE_BOX';
export const CLOSE_AGREE_BOX = 'CLOSE_AGREE_BOX';

export const SHOW_THIS_CATEGORY = 'SHOW_THIS_CATEGORY';

export const SELECTED_ADDRESS = 'SELECTED_ADDRESS';

export const SELECTED_DATE_TIME = 'SELECTED_DATE_TIME';

export const APPLY_COUPON_ON_CLICK = 'APPLY_COUPON_ON_CLICK';

export const OPEN_HELP = 'OPEN_HELP';
export const CLOSE_HELP = 'CLOSE_HELP';


export const SHOW_MESSAGE = 'SHOW_MESSAGE';


export const ADD_OR_UPDATE_ITEM = 'ADD_OR_UPDATE_ITEM';

export const INCREMENT_BAG_COUNT = 'INCREMENT_BAG_COUNT';
export const DECREMENT_BAG_COUNT = 'DECREMENT_BAG_COUNT';

export const PROCEED_TO_PAY_OPEN = 'PROCEED_TO_PAY_OPEN';

export const PROCEED_TO_PAY_CLOSE = 'PROCEED_TO_PAY_CLOSE';


export const READY_FOR_CHECK_OUT_DATA = 'READY_FOR_CHECK_OUT_DATA';
export const READY_FOR_CHECK_OUT_DATA_ADDRESS_ID = 'READY_FOR_CHECK_OUT_DATA_ADDRESS_ID';






export const SHOW_ORDER_IN_DETAILS_SUCCESS = 'SHOW_ORDER_IN_DETAILS_SUCCESS'


export const POST_TOKEN_SUCCESS = 'POST_TOKEN_SUCCESS'
export const POST_TOKEN_FAIL = 'POST_TOKEN_FAIL'

export const STORE_PATHNAME = 'STORE_PATHNAME'

export const ADD_IN_FETCH_POST = 'ADD_IN_FETCH_POST'

export const SUB_IN_FETCH_POST = 'SUB_IN_FETCH_POST'

export const STORE_CART_COUNT = 'STORE_CART_COUNT'


export const CONFIRM_LOGOUT_TRUE = 'CONFIRM_LOGOUT_TRUE'
export const CONFIRM_LOGOUT_FALSE = 'CONFIRM_LOGOUT_FALSE'

// export const PAGINATION_API_CALL_SUCCESS = ' PAGINATION_API_CALL_SUCCESS'
// export const PAGINATION_API_CALL_FAIL = ' PAGINATION_API_CALL_FAIL'