export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_ERROR = 'FETCH_ERROR';

export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

export const OPEN_REPEAT = 'OPEN_REPEAT';
export const CLOSE_REPEAT = 'CLOSE_REPEAT';

export const OPEN_VIEW_DIALOG = 'OPEN_VIEW_DIALOG';
export const CLOSE_VIEW_DIALOG = 'CLOSE_VIEW_DIALOG';

export const PROTECTED_ROUTE = 'PROTECTED_ROUTE'; 
export const ADD_PACKAGE = 'ADD_PACKAGE';

export const GET_ALL_ADDRESS = 'GET_ALL_ADDRESS';

export const OPEN_ADDRESS_ADD_DIALOG = 'OPEN_ADDRESS_ADD_DIALOG';
export const CLOSE_ADDRESS_ADD_DIALOG = 'CLOSE_ADDRESS_ADD_DIALOG';

export const OPEN_DELETE_ADDRESS_DIALOG = 'OPEN_DELETE_ADDRESS_DIALOG';
export const CLOSE_DELETE_ADDRESS_DIALOG = 'CLOSE_DELETE_ADDRESS_DIALOG';

export const OPEN_UPDATE_ADDRESS_DIALOG = 'OPEN_UPDATE_ADDRESS_DIALOG';
export const CLOSE_UPDATE_ADDRESS_DIALOG = 'CLOSE_UPDATE_ADDRESS_DIALOG';

export const APPLY_COUPON = 'APPLY_COUPON';
export const GET_SCHEDULE = 'GET_SCHEDULE';

