export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_ERROR = 'FETCH_ERROR';

export const PUBLIC_INFORMATION_SUCCESS = 'PUBLIC_INFORMATION_SUCCESS';
export const PUBLIC_INFORMATION_ERROR = 'PUBLIC_INFORMATION_ERROR';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_SIGNUP = 'USER_SIGNUP';

export const STORE_ID = 'STORE_ID';
export const ACTIVATE_USER = 'ACTIVATE_USER';

export const SUCCESS_OTP = 'SUCCESS_OTP';
export const FAIL_OTP = 'FAIL_OTP';

export const UNKNOWN_USER_SUCCESS = 'UNKNOWN_USER_SUCCESS';
export const UNKNOWN_USER_ERROR = 'UNKNOWN_USER_ERROR';

export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_MY_PROFILE_ERROR = 'GET_MY_PROFILE_ERROR';

export const UPDATE_MY_PROFILE_SUCCESS = 'UPDATE_MY_PROFILE_SUCCESS';
export const UPDATE_MY_PROFILE_ERROR = 'UPDATE_MY_PROFILE_ERROR';





export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

export const OPEN_REPEAT = 'OPEN_REPEAT';
export const CLOSE_REPEAT = 'CLOSE_REPEAT';

export const OPEN_VIEW_DIALOG = 'OPEN_VIEW_DIALOG';
export const CLOSE_VIEW_DIALOG = 'CLOSE_VIEW_DIALOG';

export const PROTECTED_ROUTE = 'PROTECTED_ROUTE';
export const ADD_PACKAGE = 'ADD_PACKAGE';

export const GET_ALL_ADDRESS = 'GET_ALL_ADDRESS';

export const OPEN_ADDRESS_ADD_DIALOG = 'OPEN_ADDRESS_ADD_DIALOG';
export const CLOSE_ADDRESS_ADD_DIALOG = 'CLOSE_ADDRESS_ADD_DIALOG';

export const OPEN_DELETE_ADDRESS_DIALOG = 'OPEN_DELETE_ADDRESS_DIALOG';
export const CLOSE_DELETE_ADDRESS_DIALOG = 'CLOSE_DELETE_ADDRESS_DIALOG';

export const OPEN_UPDATE_ADDRESS_DIALOG = 'OPEN_UPDATE_ADDRESS_DIALOG';
export const CLOSE_UPDATE_ADDRESS_DIALOG = 'CLOSE_UPDATE_ADDRESS_DIALOG';

export const APPLY_COUPON = 'APPLY_COUPON';
export const GET_SCHEDULE = 'GET_SCHEDULE';

export const GET_ORDER_DATA = 'GET_ORDER_DATA';
export const GET_ORDER_DATA_ERROR = 'GET_ORDER_DATA_ERROR';

export const SEARCH_ITEM = 'SEARCH_ITEM';
export const GET_SEARCH_TYPE = 'GET_SEARCH_TYPE';

export const BUTTON_THEME = 'BUTTON_THEME';

export const GET_THEMES = 'GET_THEMES';
export const CHANGE_THEME = 'CHANGE_THEME';

export const EMPTY_QUARRY = 'EMPTY_QUARRY';

export const OPEN_COUPON_DIALOG = 'OPEN_COUPON_DIALOG';
export const CLOSE_COUPON_DIALOG = 'CLOSE_COUPON_DIALOG';

export const SHOW_ALL_ADDRESS = 'SHOW_ALL_ADDRESS';
export const HIDE_ALL_ADDRESS = 'HIDE_ALL_ADDRESS';

export const OPEN_SCHEDULE_DIALOG = 'OPEN_SCHEDULE_DIALOG';
export const CLOSE_SCHEDULE_DIALOG = 'CLOSE_SCHEDULE_DIALOG';

export const OPEN_T_C_DIALOG = 'OPEN_T_C_DIALOG';
export const CLOSE_T_C_DIALOG = 'CLOSE_T_C_DIALOG';

export const OPEN_PROFILE_EDIT = 'OPEN_PROFILE_EDIT';
export const CLOSE_PROFILE_EDIT = 'CLOSE_PROFILE_EDIT';

export const OPEN_AGREE_BOX = 'OPEN_AGREE_BOX';
export const CLOSE_AGREE_BOX = 'CLOSE_AGREE_BOX';

export const SHOW_THIS_CATEGORY = 'SHOW_THIS_CATEGORY';

export const SELECTED_ADDRESS = 'SELECTED_ADDRESS';

export const SELECTED_DATE_TIME = 'SELECTED_DATE_TIME';

export const APPLY_COUPON_ON_CLICK = 'APPLY_COUPON_ON_CLICK';

export const OPEN_HELP = 'OPEN_HELP';
export const CLOSE_HELP = 'CLOSE_HELP';


export const SHOW_MESSAGE = 'SHOW_MESSAGE';






